{% set version = "4.35" %}

package:
  name: nspr
  version: {{ version }}

source:
  url: https://ftp.mozilla.org/pub/nspr/releases/v{{ version }}/src/nspr-{{ version }}.tar.gz
  sha256: 7ea3297ea5969b5d25a5dd8d47f2443cda88e9ee746301f6e1e1426f8a6abc8f

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('nspr', max_pin='x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - autoconf
    - sed

test:
  commands:
    - test -f ${PREFIX}/lib/libnspr4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplc4${SHLIB_EXT}
    - test -f ${PREFIX}/lib/libplds4${SHLIB_EXT}
    - test -d ${PREFIX}/include/nspr
    - test -f ${PREFIX}/bin/nspr-config

about:
  home: https://firefox-source-docs.mozilla.org/nspr/index.html
  license: MPL-2.0
  license_family: OTHER
  license_file: nspr/LICENSE
  summary: A platform-neutral API for system level and libc-like functions.
  description: |
    NetScape Portable Runtime (NSPR) provides platform independence for
    non-GUI operating system facilities. These facilities include threads,
    thread synchronization, normal file and network I/O, interval timing and
    calendar time, basic memory management (malloc and free) and shared
    library linking.
  doc_url: https://firefox-source-docs.mozilla.org/nspr/index.html
  dev_url: https://hg.mozilla.org/projects/nspr

extra:
  recipe-maintainers:
    - marcelotrevisani
    - jakirkham
