travis:
  secure:
    BINSTAR_TOKEN: RfkAJRfyyZ70gMbv/ZWEImuWXeYzi98707B9LW+CEM4Mpbn2upuUp/kvoi8CYvhNwWUgXo7nvRjaNtNLomUGkdkMvwK9+KDo//q5h8kwME60VSxc7XQIb091aSCBIOX6BHeVKRYdrKfijKHn1syirp3dsdNlN176Ot5hqC3YVI9cavIsJmJtIBG/cnJalHM2Qs9RkI0YPvDs8qm83A6szp1CWnF3itwOjrHxxmLPZL/3wEfB+SdM1JOpITOib2MwFrdssY+A6EuDzYMvS1FXtlVht4OGBEsbJ/q6VOtaOxi/UgsBB+dxBM0bC0LJtR3F76Jh460BOA2HUNL+nBGSgx9A9eVdWml2Lw1eimHTivZ9xxcZuRVaRKXYMIOMsuwbDIzpiA2+6vzccV7LUtJDMz0V3Uu+UbwOC7+qa0WEasbg6RMCy0gC9fg5kYeDAZcfnTO2aIcoO4j20w7R3c549g2vwZKMyK1B1Uz0JpAx5RLP0fjeHH6pXRcEg7Hj9dtQXjyoMAo68dFsBzBgQbTFS7T7mAt0hDWZS4CQ3vIzFDnosHR/7oX8RXO4mPIlXIOEC14oBrQxcjo+HHyzRYPqUkO3GpRRwfBFOhTj+yI7TRJwtmMUvUZCMa4YxShM05A1HP2bHwzR0NxXZxEmU2XbTEMjBDgKHrW0d4TLkkAevAk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
